language: node_js
node_js:
  - 12
script: yarn lint && yarn build && ./scripts/test_e2e.sh
cache:
  yarn: true
  directories:
    - /home/travis/.cache/Cypress
addons:
  apt:
    packages:
      - libgconf-2-4
